### ISSUE TITLE
🚀 [Feature] Add Locales EN, FR

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/ocelot.social#138]
## 🚀 Feature

Add Languages EN, FR.

**English translation:** 
[ocelot.social-website-content-en.odt](https://github.com/Ocelot-Social-Community/ocelot.social/files/15418377/ocelot.social-website-content-en.odt)

**French translation:**
[ocelot.social-website-content-fr.odt](https://github.com/Ocelot-Social-Community/ocelot.social/files/15418724/ocelot.social-website-content-fr.odt)

### Todo

- [x] German: Footer: Chance "Authoren" to "Autoren" or "Freunde"
- [x] donate – care for @Elweyn suggestions:
  - [x] https://github.com/Ocelot-Social-Community/ocelot.social/pull/55#discussion_r1530209921
  - [x] https://github.com/Ocelot-Social-Community/ocelot.social/pull/55#discussion_r1530221074
- [ ] description, see https://github.com/Ocelot-Social-Community/ocelot.social/issues/26#issuecomment-2126660467

#### DevOps

- [ ] there is a short blink of `404` on URL `http://localhost:8080/` before it switches to `http://localhost:8080/de/`
- [ ] do we have to set again `redirect: { autoLocale: true }` ?
- [ ] #139
