### ISSUE TITLE
🐛 [Bug] Fix Some Content Issues

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/ocelot.social#152]
## 🐛 Bugreport

Fix Some Content Issues

### Todo

- [ ] English: Contribute page: Delete the link "Organisierst du gerne?"
- [ ] English: Contribute page: Change heading "Make the ocelot.social software known" to "Promote the ocelot.social software".
- [ ] All languages: Contribute page: Operate your own network: Link to the "Get started" page (instead of the documentation).
